import type { TargetResult } from "./api.ts";
import auditFixes from "./knowledge/audit-fixes.json" with { type: "json" };

interface FixInfo {
  why: string;
  fix: string;
}

const FIXES: Record<string, FixInfo> = auditFixes;

export function terminalReport(result: TargetResult): string {
  const lines: string[] = [
    `\n=== ${result.url} — ${result.formFactor.toUpperCase()} ===`,
    Object.entries(result.scores).map(([k, v]) => `${k}: ${v}`).join("  |  "),
    "",
  ];
  for (const { title, gaps } of result.gaps) {
    lines.push(`  ${title} gaps:`);
    for (const gap of gaps) {
      lines.push(`    - ${gap.id}: ${gap.score}%${gap.displayValue ? ` (${gap.displayValue})` : ""}`);
    }
  }
  return lines.join("\n");
}

export function toMarkdown(results: TargetResult[]): string {
  const md: string[] = ["# Lighthouse Report", ""];
  const byUrl = new Map<string, TargetResult[]>();
  for (const r of results) {
    byUrl.set(r.url, [...(byUrl.get(r.url) ?? []), r]);
  }

  for (const [url, urlResults] of byUrl) {
    md.push(`## ${url}`, "");

    md.push("| Form Factor | " + Object.keys(urlResults[0]?.scores ?? {}).join(" | ") + " |");
    md.push("| --- | " + Object.keys(urlResults[0]?.scores ?? {}).map(() => "---").join(" | ") + " |");
    for (const r of urlResults) {
      md.push(`| ${r.formFactor} | ` + Object.values(r.scores).join(" | ") + " |");
    }
    md.push("");

    for (const r of urlResults) {
      md.push(`### ${r.formFactor} — issues to fix, ranked by impact`, "");
      if (!r.gaps.length) {
        md.push("No issues below 100%. 🎉", "");
        continue;
      }
      for (const cat of r.gaps) {
        md.push(`#### ${cat.title}`, "");
        for (const gap of cat.gaps) {
          const info = FIXES[gap.id];
          md.push(`- **${gap.title}** (\`${gap.id}\`) — ${gap.score}%${gap.displayValue ? ` — ${gap.displayValue}` : ""}`);
          if (info) {
            md.push(`  - Why: ${info.why}`);
            md.push(`  - Fix: ${info.fix}`);
          }
        }
        md.push("");
      }
    }
  }

  md.push(
    "---",
    "",
    "_Generated by lightscore. Feed this file to a coding agent (e.g. `claude \"fix the issues in lighthouse-report.md\"`) to act on the fixes above._",
  );

  return md.join("\n");
}
